name: Playwright Tests

# run when commits are pushed to master and when PRs target master
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  e2e:
    name: Run Playwright E2E
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Node
        uses: actions/setup-node@v5
        with:
          node-version: lts/*

      - name: Install dependencies
        run: npm ci

      # This action installs Playwright browsers and recommended system deps
      - name: Install Playwright browsers & deps
        uses: microsoft/playwright-github-action@v1
        with:
          browsers: chromium,firefox,webkit

      - name: Run Playwright tests
        # Playwright's webServer in playwright.config.ts will build + serve your app
        run: npx playwright test --reporter=list
        env:
          CI: true

      - name: Upload Playwright HTML report (artifact)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report
