name: Playwright Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  e2e:
    name: Run Playwright E2E
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Node
        uses: actions/setup-node@v5
        with:
          node-version: lts/*

      - name: Install dependencies
        run: npm ci

      # ✅ New step — install Playwright browsers AND system dependencies
      - name: Install Playwright browsers & system deps
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: npx playwright test --reporter=list
        env:
          CI: true

      # Optional: save the HTML report as an artifact
      - name: Upload Playwright HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report
